from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
OUTPUT_DIR = DATA_DIR / "outputs"
REVIEW_DIR = OUTPUT_DIR / "review"

RECOMMENDED_FILE = RAW_DIR / "mplads_recommended_works_2026-08-23.csv"
COMPLETED_FILE = RAW_DIR / "mplads_completed_works_2026-08-23.csv"
EXPENDITURE_FILE = RAW_DIR / "mplads_expenditures_2026-08-23.csv"
MP_SUMMARY_FILE = RAW_DIR / "mplads_mp_summary_2026-08-23.csv"

# Matching thresholds. Scores are 0-100.
TIER1_THRESHOLD = 88.0
TIER2_THRESHOLD = 78.0
MIN_MARGIN_TIER1 = 8.0
MIN_MARGIN_TIER2 = 4.0
MAX_CANDIDATES_PER_REC = 10
DATE_WINDOW_DAYS = 900
TIER1_DESC_FLOOR = 90.0
TIER2_DESC_FLOOR = 78.0
STRONG_CONTEXT_THRESHOLD = 97.0
MAX_BLOCK_SIZE_FOR_FUZZY = 1200

# Contradiction penalties.
PENALTY_IDA_MISMATCH = 14.0
PENALTY_CATEGORY_MISMATCH = 10.0
PENALTY_ENTITY_MISMATCH = 8.0
PENALTY_WEAK_ANCHORS = 6.0

# Risk thresholds.
HIGH_RISK = 70.0
MEDIUM_RISK = 45.0

# Statistical peer-group rules.
MIN_PEER_GROUP_SIZE = 15

# Expenditure indicators are intentionally MP/IDA aggregate-level.
PAYMENT_MISMATCH_MIN_ABS = 500_000.0
PAYMENT_MISMATCH_MIN_PCT = 25.0
VENDOR_CONCENTRATION_FLAG_PCT = 35.0
VENDOR_HIGH_PCT = 60.0

RANDOM_STATE = 42
